import { createElement } from 'lwc';
import XSWYT_WishlistButtonFA from 'c/xSWYT_WishlistButtonFA';

describe('c-x-s-w-y-t-wishlist-button-fa', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-x-s-w-y-t-wishlist-button-fa', {
            is: XSWYT_WishlistButtonFA
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});